apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.appSetName }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
  - clusters: 
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
        matchExpressions:
          - key: type
            operator: NotIn
            values:
              - prod
  template:
    metadata:
      name: '{{ .Values.projectName }}-{{ "{{ name }}" }}'
      namespace: {{ .Values.namespace }}
    spec:
      project: default
      source:
        repoURL: https://github.com/DavidDaskalo/distributed-argocd-demo.git
        targetRevision: main
        path: argo-core-files
      destination:
        name: '{{ "{{ name }}" }}'
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true